name: Publish Python Package to GitHub Packages

on:
  push:
    branches:
      - master


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Construir o pacote
        run: |
          python setup.py sdist

      - name: Upload para GitHub Packages
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          twine upload --repository-url https://pypi.pkg.github.com/jocimar-dev dist/*
